const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src/saga-merk.js'), 'utf8');
const template = fs.readFileSync(path.join(root, 'src/installer.html'), 'utf8');
const bookmarklet = 'javascript:' + encodeURIComponent(source);
const escape = value => value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#x27;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const html = template.replaceAll('{{BOOKMARKLET}}', escape(bookmarklet)).replace('{{SOURCE}}', () => source).replace('{{SITE_SCRIPT}}', () => fs.readFileSync(path.join(root, 'src/site.js'), 'utf8'));
if (html.includes('{{BOOKMARKLET}}') || html.includes('{{SOURCE}}') || html.includes('{{SITE_SCRIPT}}')) throw new Error('Unresolved installer placeholder');
const dist = path.join(root, 'dist');
fs.mkdirSync(dist, { recursive: true });
fs.writeFileSync(path.join(dist, 'saga-merk.js'), source);
fs.writeFileSync(path.join(dist, 'saga-merk-bookmarklet.txt'), bookmarklet);
fs.writeFileSync(path.join(root, 'index.html'), html);
console.log(`Built standalone index.html and bookmarklet (${Buffer.byteLength(bookmarklet).toLocaleString()} bytes).`);
